# Generated by Django 4.2.18 on 2025-03-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="team", name="members",),
        migrations.RemoveField(model_name="team", name="name",),
        migrations.AddField(
            model_name="team",
            name="diversify_gender",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="team", name="genders", field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="team",
            name="match_preferences",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="team",
            name="student_numbers",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="team", name="students", field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="team", name="team_size", field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="team",
            name="title",
            field=models.CharField(default="Untitled Team", max_length=255),
        ),
    ]
