# Generated by Django 4.2.18 on 2025-03-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_team_members_remove_team_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=10, unique=True)),
                ("gender", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("academicHistory", models.CharField(max_length=100)),
                ("timeSlot", models.CharField(max_length=20)),
                ("enemy", models.CharField(max_length=100)),
                ("PM", models.CharField(max_length=100)),
                ("projectPreference", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(model_name="team", name="diversify_gender",),
        migrations.RemoveField(model_name="team", name="genders",),
        migrations.RemoveField(model_name="team", name="match_preferences",),
        migrations.RemoveField(model_name="team", name="student_numbers",),
        migrations.RemoveField(model_name="team", name="students",),
        migrations.RemoveField(model_name="team", name="team_size",),
        migrations.RemoveField(model_name="team", name="title",),
        migrations.AddField(
            model_name="team",
            name="color",
            field=models.CharField(default="green", max_length=50),
        ),
        migrations.AddField(
            model_name="team",
            name="name",
            field=models.CharField(default="team", max_length=100),
        ),
        migrations.CreateModel(
            name="TeamGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generate_team_name", models.CharField(max_length=100, unique=True)),
                ("diversify_gender", models.BooleanField(default=False)),
                ("match_preferences", models.BooleanField(default=False)),
                ("people_per_team", models.IntegerField(default=1)),
                (
                    "teams",
                    models.ManyToManyField(
                        related_name="team_generations", to="api.team"
                    ),
                ),
            ],
        ),
    ]
