# Generated by Django 4.2.18 on 2025-03-13 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_team_students"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student", old_name="student_id", new_name="studentID",
        ),
    ]
