# Generated by Django 4.2.18 on 2025-03-13 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_student_id_student_studentid"),
    ]

    operations = [
        migrations.RemoveField(model_name="teamgeneration", name="people_per_team",),
    ]
