# Generated by Django 4.2.18 on 2025-03-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_teamgeneration_people_per_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="project",
            field=models.CharField(default="project_1", max_length=50),
        ),
    ]
