# Generated by Django 4.2.18 on 2025-04-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_team_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="color",
            field=models.CharField(default="#FF9180", max_length=50),
        ),
    ]
